### ISSUE TITLE
puppetlabs/apt 1.8.0 only

### ISSUE THREAD

**Issue by damiandennis** [garethr/garethr-docker#455] opened 2016-03-01 19:21 UTC
Currently this module is only compatible with puppetlabs/apt v1.8.0 and no later. As you can see in the changelog 
https://github.com/puppetlabs/puppetlabs-apt/blob/master/CHANGELOG.md
they have removed a bunch of parameters in 2.0.0

**Comment by JPalmerGithub** [comment] 2016-03-04 17:05
Hi Damian & Gareth,
Yes, I have experienced similar issues. However, managed to fix it as the diff below.
I am sure it can be more elaborated, as parameterising etc.

garethr-docker (v5.1.0)
puppetlabs-apt (v2.2.2)
PUPPET Enterprise v2015.3.1
Ubuntu 14.04.4 LTS

[docker.txt](https://github.com/garethr/garethr-docker/files/159059/docker.txt)

**Comment by garethr** [comment] 2016-03-29 13:24
Closing in favour of #459. The issue is a backwards incompatible release of the apt module is coming at some point.

**Closed by garethr** 2016-03-29 13:24 UTC
