### ISSUE TITLE
Questions: do we support "--entrypoint" parameter of in docker::run?

### ISSUE THREAD

**Issue by zhifengMaBeijing** [garethr/garethr-docker#487] opened 2016-03-25 02:43 UTC
Hi Gareth,
sorry i put a question here in the issue list. because i  do not where to post this question.
with docker itself, i could use --entrypoint to overwrite the entry of a docker image as follows: 
docker run --entrypoint=/bin/sh -t <mydockerimage>

my question is how could i achieve that with docker::run puppet type?

regards,
Zhifeng
zhifeng.ma@thomsonreuters.com

**Comment by garethr** [comment] 2016-03-25 09:22
@zhifengMaBeijing mm, it doesn't look like run has native support for this, but you can still pass entrypoint via `extra_parameters` described here: https://github.com/garethr/garethr-docker/blob/master/manifests/run.pp#L41-L44

**Comment by garethr** [comment] 2016-03-29 13:29
I just noticed this is a duplicate of #303 so I'll close this in favour of that issue.

**Closed by garethr** 2016-03-29 13:29 UTC
Labels: feature

**Comment by zhifengMaBeijing** [comment] 2016-04-04 06:16
thanks garethr. i could use extra_parameters.
