### ISSUE TITLE
dm_basesize does not get updated in /etc/sysconfig/docker-storage

### ISSUE THREAD

**Issue by craigbarrau** [garethr/garethr-docker#270] opened 2015-06-16 01:31 UTC
The following will setup docker but it does not add the line " --storage-opt dm.basesize=20GB" to /etc/sysconfig/docker-storage as expected.
`class { 'docker':
  dm_basesize => '20G',
}`

Unless I am missing something really obvious the issue appears to be that dm_basesize is available in init.pp scope but not service.pp. Simple logging using notice function proved this.

**Comment by n0coast** [comment] 2015-08-07 23:48
If you read through the template (templates/etc/sysconfig/docker-storage) you'll see that the line that would populate dm_basesize is wrapped in an 'if' statement, so you need to specify your storage driver as devicemapper to get dm_basesize to populate.

DOCKER_STORAGE_OPTIONS="<% -%>
<% if @storage_driver %> --storage-driver=<%= @storage_driver %><% end -%>
<% if @storage_driver == 'devicemapper' -%>
<% if @dm_basesize %> --storage-opt dm.basesize=<%= @dm_basesize %><% end -%>
<% if @dm_fs %> --storage-opt dm.fs=<%= @dm_fs %><% end -%>
<% if @dm_mkfsarg %> --storage-opt "dm.mkfsarg=<%= @dm_mkfsarg %>"<% end -%>
<% if @dm_mountopt %> --storage-opt dm.mountopt=<%= @dm_mountopt %><% end -%>
<% if @dm_blocksize %> --storage-opt dm.blocksize=<%= @dm_blocksize %><% end -%>
<% if @dm_loopdatasize %> --storage-opt dm.loopdatasize=<%= @dm_loopdatasize %><% end -%>
<% if @dm_loopmetadatasize %> --storage-opt dm.loopmetadatasize=<%= @dm_loopmetadatasize %><% end -%>
<% if @dm_datadev %> --storage-opt dm.datadev=<%= @dm_datadev %><% end -%>
<% if @dm_metadatadev %> --storage-opt dm.metadatadev=<%= @dm_metadatadev %><% end -%>
<% end -%>
"

**Comment by garethr** [comment] 2015-08-22 18:22
@n0coast thanks for the help there. I'll leave this open as it would be nice to prompt the user that `bd_basesize` or other params are being ignored in this case.

**Comment by n0coast** [comment] 2015-08-25 17:25
https://github.com/garethr/garethr-docker/pull/335 created to notify user of this case.

**Comment by madAndroid** [comment] 2015-11-05 09:21
I've run into this as well, and it appears as though @craigbarrau is correct - there's no `@dm_basesize` defined in the params in the service class, so there's no way it would be in scope, even if you set `storage_driver` to `devicemapper`.

**Comment by madAndroid** [comment] 2015-11-12 04:22
Looks like this was fixed in 1a10968e18765da5584e720df49eb7750adf0b13 - which in not on the forge yet, afaict

**Comment by garethr** [comment] 2015-11-13 11:17
@madAndroid  thanks for the prompt.

**Closed by garethr** 2015-11-13 11:17 UTC

**Comment by madAndroid** [comment] 2015-11-13 11:19
I think this may still be occurring .. I'll reopen if it does - that commit I linked to doesn't have changes in the `service.pp` to address the missing storage params. As soon as I've got a bit of time, I'll double check whether this is still causing an issue, and send a PR with a fix if it is.

**Comment by madAndroid** [comment] 2015-11-14 16:22
This is very very interesting ... when the future parser is enabled in `3.x`, then the required variables are not in scope of the `docker::service` class, and only exist in the parent class' scope. I've confirmed this in a beaker run when setting `parser=future` in the puppet.conf, and this is the exact same behaviour I'm seeing. I'll open a pull request for the addition of the other `dm_` variables to the `docker::service` class, as this feels like some sort of scope leaking, that these variables should indeed not be present in the current scope.
