### ISSUE TITLE
Environment variables in docker_run_flags need to be quoted

### ISSUE THREAD

**Issue by lorijean44** [garethr/garethr-docker#409] opened 2016-01-19 15:23 UTC
It is possible to pass environment variables that have spaces in them.  However the docker_run_flags function does not handle that.

By putting quotes, this should be sufficient.

**Comment by garethr** [comment] 2016-01-19 16:11
I think this is a duplicate of https://github.com/garethr/garethr-docker/issues/367? If not let me know and I'll reopen. Thanks for reporting the issue.

**Closed by garethr** 2016-01-19 16:11 UTC
