### ISSUE TITLE
detach_service_in_init with false on amazon linux

### ISSUE THREAD

**Issue by stupied4ever** [garethr/garethr-docker#392] opened 2015-12-09 18:05 UTC
I am using Amazon Linux with this module to handle the docker containers, and the puppet never finish to apply. After a little dive on the code, I discovered that detach_service_in_init is set to false on this OS.

I really did not understand why this value is set to false by default, could you explain?

**Comment by garethr** [comment] 2015-12-10 08:50
I don't have explicit support for Amazon Linux, but some users have reported success. The relevant issues are: https://github.com/garethr/garethr-docker/pulls?q=is%3Apr+amazon+is%3Aclosed. Worth checking with @ikalinin and @ryfow

**Comment by ikalinin** [comment] 2015-12-10 18:58
I am using a pretty old version of this module (from April), and this is a fairly new addition, but it's pretty clear that the issue is the same as what #232 was targeting to fix. $operatingsystemrelease has "20XX.XX" format on Amazon Linux, which is greater than 7.0, while Amazon Linux is actually using sysv init, which is more in line with earlier RHEL releases. Look for solution I came up with in the pull request I mentioned above, it will be exactly the same.

**Comment by garethr** [comment] 2016-02-08 15:20
Hopefully this is now fixed in https://github.com/garethr/garethr-docker/pull/418. If not let me know.

**Closed by garethr** 2016-02-08 15:20 UTC
Labels: bug
