### ISSUE TITLE
Scope(Apt::Source ... warnings during setup

### ISSUE THREAD

**Issue by ascheman** [garethr/garethr-docker#479] opened 2016-03-18 07:42 UTC
It seems the module needs some cleanup. The following warnings are printed during manifest application:

```
==> default: Warning: Scope(Apt::Source[docker]): $include_src is deprecated and will be removed in the next major release, please use $include => { 'src' => false } instead
==> default: Warning: Scope(Apt::Source[docker]): $required_packages is deprecated and will be removed in the next major release, please use package resources instead.
==> default: Warning: Scope(Apt::Source[docker]): $key_source is deprecated and will be removed in the next major release, please use $key => { 'source' => https://apt.dockerproject.org/gpg } instead.
==> default: Warning: Scope(Apt::Key[Add key: 58118E89F3A912897C070ADBF76221572C52609D from Apt::Source docker]): $key_source is deprecated and will be removed in the next major release. Please use $source instead.
```

**Comment by garethr** [comment] 2016-03-29 13:24
Closing in favour of #459. The issue is a backwards incompatible release of the apt module is coming at some point.

**Closed by garethr** 2016-03-29 13:24 UTC
